#!/usr/bin/env python3
"""Saakshi Recovery Validation Script.

Purpose:
    Compare the SegmentRecords recovered by the NAL carver / GOP repair
    pipeline against a ground_truth.json produced by make_synthetic_dvr.py.
    Computes precision, recall, byte-level recovery rate, and per-clip
    status (exact / partial / missed / false-positive).

    ⚠ WARNING: All results produced by this script reflect SYNTHETIC data
    generated by make_synthetic_dvr.py.  They MUST NOT be presented as
    real-device performance metrics in any judicial, regulatory, or
    competitive submission.  Real-device validation requires controlled lab
    experiments with certified reference hardware.

Inputs:
    disk_image:       Path to the synthetic .img file.
    ground_truth:     Path to ground_truth.json from make_synthetic_dvr.py.

Outputs:
    Human-readable table on stdout.
    JSON report written to docs/validation/<run_id>_results.json.

Status: Implemented (synthetic validation only).
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Ensure backend app is on the path when run from repo root
_REPO_ROOT = Path(__file__).resolve().parent.parent
_BACKEND = _REPO_ROOT / "saakshi" / "backend"
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))
# Also try relative (when run from saakshi/ root)
_BACKEND_ALT = Path(__file__).resolve().parent.parent / "backend"
if _BACKEND_ALT.exists() and str(_BACKEND_ALT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ALT))

from app.modules.recovery.gop_repair import repair_gops  # noqa: E402
from app.modules.recovery.nal_carver import default_nal_carver, group_into_gops  # noqa: E402

# ──────────────────────────────────────────────────────────────────────────────
# Matching logic
# ──────────────────────────────────────────────────────────────────────────────

OVERLAP_THRESHOLD = 0.50   # 50 % byte overlap to count as a hit


def _byte_overlap_ratio(a_start: int, a_end: int, b_start: int, b_end: int) -> float:
    """Fraction of clip A that overlaps with segment B.

    Returns value in [0, 1].
    """
    overlap = max(0, min(a_end, b_end) - max(a_start, b_start))
    a_len = a_end - a_start
    if a_len <= 0:
        return 0.0
    return overlap / a_len


def _match_clips_to_segments(
    gt_clips: list[dict[str, Any]],
    recovered_segments: list[dict[str, Any]],
) -> dict[str, Any]:
    """Match each ground-truth clip to recovered segments by combined byte coverage.

    The carver may split a single DVR clip into multiple GOPs.  We therefore
    compute the *total* fraction of the clip that is covered by the union of
    all overlapping recovered segments (byte-level union, not sum).

    A ground-truth clip is:
    - 'exact'   if the union of all matching segments covers ≥ 90 % of the clip
    - 'partial' if the union covers [50%, 90%) of the clip
    - 'missed'  if the union covers < 50 % of the clip

    A recovered segment is a 'false_positive' if it does not overlap with any
    non-overwritten ground-truth clip at the segment-perspective (i.e. the
    segment itself is ≥ 50 % outside all clips).

    Args:
        gt_clips:            List of clip dicts from ground_truth.json.
        recovered_segments:  List of dicts with 'offset' and 'length'.

    Returns:
        Dict with categorised clip IDs and lists.
    """
    exact: list[int] = []
    partial: list[int] = []
    missed: list[int] = []
    matched_seg_indices: set[int] = set()

    # Only evaluate clips that are not overwritten (overwritten data is truly gone)
    evaluable = [c for c in gt_clips if not c.get("overwritten", False)]
    deleted = [c for c in gt_clips if c.get("deleted", False) and not c.get("overwritten", False)]

    for clip in evaluable:
        c_start = clip["abs_start_byte"]
        # Use actual content length (not sector-padded abs_end_byte) for matching
        byte_length = clip.get("byte_length", clip["abs_end_byte"] - clip["abs_start_byte"])
        c_end = c_start + byte_length
        c_len = c_end - c_start
        if c_len <= 0:
            missed.append(clip["clip_id"])
            continue

        # Build a coverage boolean array over the clip's byte range
        covered = bytearray(c_len)  # 0 = not covered, 1 = covered
        segs_contributing: list[int] = []

        for seg_idx, seg in enumerate(recovered_segments):
            s_start = seg["offset"]
            s_end = seg["offset"] + seg["length"]
            ov_start = max(c_start, s_start)
            ov_end = min(c_end, s_end)
            if ov_end > ov_start:
                # Mark covered bytes
                for b in range(ov_start - c_start, ov_end - c_start):
                    covered[b] = 1
                segs_contributing.append(seg_idx)

        coverage_ratio = sum(covered) / c_len

        if coverage_ratio >= 0.90:
            exact.append(clip["clip_id"])
            matched_seg_indices.update(segs_contributing)
        elif coverage_ratio >= OVERLAP_THRESHOLD:
            partial.append(clip["clip_id"])
            matched_seg_indices.update(segs_contributing)
        else:
            missed.append(clip["clip_id"])

    # False positives: recovered segments whose content lies mostly outside all clips
    false_positives: list[int] = []
    for seg_idx, seg in enumerate(recovered_segments):
        if seg_idx in matched_seg_indices:
            continue
        s_start = seg["offset"]
        s_end = seg["offset"] + seg["length"]
        s_len = s_end - s_start
        if s_len <= 0:
            false_positives.append(seg_idx)
            continue
        # How much of this segment overlaps with any evaluable clip?
        total_in_clip = 0
        for clip in evaluable:
            clip_start = clip["abs_start_byte"]
            clip_len = clip.get("byte_length", clip["abs_end_byte"] - clip["abs_start_byte"])
            clip_end = clip_start + clip_len
            ov = max(0, min(s_end, clip_end) - max(s_start, clip_start))
            total_in_clip += ov
        if total_in_clip / s_len < OVERLAP_THRESHOLD:
            false_positives.append(seg_idx)

    return {
        "exact": exact,
        "partial": partial,
        "missed": missed,
        "false_positives": false_positives,
        "deleted_clip_ids": [c["clip_id"] for c in deleted],
        "evaluable_count": len(evaluable),
    }



def _byte_recovery_rate(
    gt_clips: list[dict[str, Any]],
    recovered_segments: list[dict[str, Any]],
) -> float:
    """Compute the fraction of evaluable ground-truth bytes that are recovered.

    'Recovered' means a recovered segment overlaps with the ground-truth byte.
    """
    evaluable = [c for c in gt_clips if not c.get("overwritten", False)]

    # Build a coverage bitmap using ranges
    total_gt_bytes = 0
    recovered_bytes = 0

    for clip in evaluable:
        c_start = clip["abs_start_byte"]
        c_end = clip["abs_end_byte"]
        c_len = c_end - c_start
        total_gt_bytes += c_len

        # How many of these bytes are covered by any recovered segment?
        covered = [False] * c_len
        for seg in recovered_segments:
            s_start = seg["offset"]
            s_end = seg["offset"] + seg["length"]
            ov_start = max(c_start, s_start)
            ov_end = min(c_end, s_end)
            for b in range(ov_start - c_start, max(0, ov_end - c_start)):
                covered[b] = True
        recovered_bytes += sum(covered)

    if total_gt_bytes == 0:
        return 1.0
    return recovered_bytes / total_gt_bytes


# ──────────────────────────────────────────────────────────────────────────────
# Main pipeline
# ──────────────────────────────────────────────────────────────────────────────

def run_validation(
    disk_image: Path,
    ground_truth: Path,
    out_dir: Path,
    min_confidence: float = 0.0,
    run_repair: bool = True,
) -> dict[str, Any]:
    """Run the full carve → repair → match → metrics pipeline.

    Args:
        disk_image:     Path to synthetic_dvr.img.
        ground_truth:   Path to ground_truth.json.
        out_dir:        Directory for JSON report output.
        min_confidence: Discard segments below this confidence (0.0 = keep all).
        run_repair:     Whether to run GOP repair before validation.

    Returns:
        Full result dict (same as written to JSON).
    """
    gt = json.loads(ground_truth.read_text())
    gt_clips: list[dict[str, Any]] = gt["clips"]

    # Read disk image
    source_data = disk_image.read_bytes()

    # Carve NAL units
    from io import BytesIO
    carver = default_nal_carver
    nal_units = list(carver.carve_stream(BytesIO(source_data)))

    # Group into GOPs
    segments = group_into_gops(nal_units, stream_data=source_data)

    pre_repair_count = len(segments)
    pre_repair_confidences = [s.confidence for s in segments]

    # GOP repair
    repaired_count = 0
    if run_repair:
        repair_result = repair_gops(segments, source=source_data)
        segments = repair_result.segments
        repaired_count = repair_result.repaired_count

    # Filter by confidence
    if min_confidence > 0.0:
        segments = [s for s in segments if s.confidence >= min_confidence]

    recovered_dicts = [{"offset": s.offset, "length": s.length, "confidence": s.confidence} for s in segments]

    # Match & score
    match_result = _match_clips_to_segments(gt_clips, recovered_dicts)
    byte_rate = _byte_recovery_rate(gt_clips, recovered_dicts)

    evaluable = match_result["evaluable_count"]
    n_exact = len(match_result["exact"])
    n_partial = len(match_result["partial"])
    n_missed = len(match_result["missed"])
    n_fp = len(match_result["false_positives"])

    # Precision = TP / (TP + FP)
    tp = n_exact + n_partial
    precision = tp / (tp + n_fp) if (tp + n_fp) > 0 else 0.0
    recall = tp / evaluable if evaluable > 0 else 0.0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0

    out = {
        "run_metadata": {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "disk_image": str(disk_image.resolve()),
            "ground_truth": str(ground_truth.resolve()),
            "source_bytes": len(source_data),
            "gt_total_clips": len(gt_clips),
            "gt_evaluable_clips": evaluable,
            "gt_deleted_clips": len(match_result["deleted_clip_ids"]),
            "warning": (
                "SYNTHETIC DATA ONLY. Results must NOT be presented as "
                "real-device performance. See docs/validation/validation-plan.md."
            ),
        },
        "carver_stats": {
            "nal_units_carved": len(nal_units),
            "pre_repair_segments": pre_repair_count,
            "repaired_segments": repaired_count,
            "final_segments": len(recovered_dicts),
            "min_confidence_filter": min_confidence,
            "avg_pre_repair_confidence": (
                sum(pre_repair_confidences) / len(pre_repair_confidences)
                if pre_repair_confidences else 0.0
            ),
        },
        "metrics": {
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "f1": round(f1, 4),
            "byte_recovery_rate": round(byte_rate, 4),
            "exact_matches": n_exact,
            "partial_matches": n_partial,
            "missed": n_missed,
            "false_positives": n_fp,
        },
        "clip_detail": match_result,
    }

    # Write JSON report
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    report_path = out_dir / f"synthetic_validation_{ts}.json"
    report_path.write_text(json.dumps(out, indent=2))

    return out


# ──────────────────────────────────────────────────────────────────────────────
# Human-readable table
# ──────────────────────────────────────────────────────────────────────────────

def _print_table(result: dict[str, Any]) -> None:
    m = result["metrics"]
    cs = result["carver_stats"]
    rm = result["run_metadata"]

    print()
    print("=" * 60)
    print("  SAAKSHI RECOVERY VALIDATION REPORT (SYNTHETIC DATA)")
    print("=" * 60)
    print(f"  ⚠  {rm['warning'][:60]}")
    print(f"     (see docs/validation/validation-plan.md)")
    print("-" * 60)
    print(f"  Disk image        : {Path(rm['disk_image']).name}")
    print(f"  Ground-truth clips: {rm['gt_total_clips']}  "
          f"(evaluable: {rm['gt_evaluable_clips']}, deleted: {rm['gt_deleted_clips']})")
    print(f"  NAL units carved  : {cs['nal_units_carved']}")
    print(f"  Segments (pre-repair) : {cs['pre_repair_segments']}")
    print(f"  Segments repaired : {cs['repaired_segments']}")
    print(f"  Segments (final)  : {cs['final_segments']}")
    print("-" * 60)
    print(f"  Precision         : {m['precision']:.1%}")
    print(f"  Recall            : {m['recall']:.1%}")
    print(f"  F1                : {m['f1']:.1%}")
    print(f"  Byte recovery rate: {m['byte_recovery_rate']:.1%}")
    print("-" * 60)
    print(f"  Exact matches     : {m['exact_matches']}")
    print(f"  Partial matches   : {m['partial_matches']}")
    print(f"  Missed            : {m['missed']}")
    print(f"  False positives   : {m['false_positives']}")
    print("=" * 60)
    print()


# ──────────────────────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate Saakshi recovery against synthetic ground truth."
    )
    parser.add_argument(
        "disk_image",
        type=Path,
        help="Path to synthetic_dvr.img",
    )
    parser.add_argument(
        "ground_truth",
        type=Path,
        help="Path to ground_truth.json",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("docs/validation"),
        help="Directory for JSON report (default: docs/validation/)",
    )
    parser.add_argument(
        "--min-confidence",
        type=float,
        default=0.0,
        help="Discard recovered segments below this confidence score (0.0 = keep all)",
    )
    parser.add_argument(
        "--no-repair",
        action="store_true",
        help="Skip GOP repair pass",
    )
    args = parser.parse_args()

    result = run_validation(
        disk_image=args.disk_image,
        ground_truth=args.ground_truth,
        out_dir=args.out_dir,
        min_confidence=args.min_confidence,
        run_repair=not args.no_repair,
    )
    _print_table(result)
    report_path = list(args.out_dir.glob("synthetic_validation_*.json"))
    if report_path:
        print(f"Report written to: {sorted(report_path)[-1]}")


if __name__ == "__main__":
    main()
